### ISSUE TITLE
Mod failed to load with latest version of Forge

### ISSUE THREAD

**Issue by Gamemassa** [Nosiphus/nosiphus-furniture#3]
Minecraft version: 1.19
Forge version: 41.0.96
Mod version: 7.2

-- Head --
Thread: Render thread
Stacktrace:
	at com.nosiphus.furniture.core.ModBlockEntities.<clinit>(ModBlockEntities.java:18) ~[nfm-2022.07.02-1.19.jar%23185!/:task ':jar' property 'archiveVersion'] {re:classloading,pl:epic_rei_lmao:B}
-- MOD nfm --
Details:
	Caused by 0: java.lang.reflect.InvocationTargetException
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.0.96.jar%23202!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.96.jar%23201!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: nfm-2022.07.02-1.19.jar
	Failure message: Nosiphus Furniture Mod (nfm) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 2022.07.02
	Mod Issue URL: https://github.com/Nosiphus/nosiphus-furniture-mod/issues
	Exception message: java.lang.NoSuchFieldError: BLOCK_ENTITIES
Stacktrace:
	at com.nosiphus.furniture.core.ModBlockEntities.<clinit>(ModBlockEntities.java:18) ~[nfm-2022.07.02-1.19.jar%23185!/:task ':jar' property 'archiveVersion'] {re:classloading,pl:epic_rei_lmao:B}
	at com.nosiphus.furniture.NosiphusFurnitureMod.<init>(NosiphusFurnitureMod.java:29) ~[nfm-2022.07.02-1.19.jar%23185!/:task ':jar' property 'archiveVersion'] {re:classloading,pl:epic_rei_lmao:B}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19-41.0.96.jar%23202!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.96.jar%23201!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

[crash-2022-07-12_12.26.33-fml.txt](https://github.com/Nosiphus/nosiphus-furniture-mod/files/9095089/crash-2022-07-12_12.26.33-fml.txt)

**Comment by seancrain** [comment]
This issue was fixed in the 2022.07.15 build.
